### ISSUE TITLE
Error starting userland proxy: listen tcp4 127.0.0.1:80: bind: address already in use

### ISSUE THREAD

**Issue by thunderwin** [inovector/mixpost#101]
### Detailed description

I have a brand new server installed, using docker to install mixport having this isuue.. how come..

**Comment by Subtixx** [comment]
Check what is using port 80
`netstat -tulpn | grep :80`

**Comment by lao9s** [comment]
@thunderwin To generate SSL certificates, ensure that port 80 is free on your machine. If it is not, please use the `docker-compose.yml `file from the `Without SSL Support` tab and handle SSL certificates separately.
