### ISSUE TITLE
Where is the

### ISSUE THREAD

**Issue by defcon8** [inovector/mixpost#108]
### Detailed description

According to the manual I need to create the "Terms of Use" and "Privacy policy" pages for Facebook within Mixpost. It says;

 "In Mixpost Dashboard, navigate to the Admin Console then click on Pages."
Source; https://docs.mixpost.app/pages

But I have no "Admin Console" in my Mixpost UI?
![Screenshot 2024-07-13 at 16 50 09](https://github.com/user-attachments/assets/3382a4d0-6e52-4d67-b956-27f79245af1e)

**Comment by uhlhosting** [comment]
One needs to have the Enterprise release to do so I think.

**Comment by lao9s** [comment]
The `Pages` section is available only on the Pro/Enterprise package. However, for personal use (Lite package), there is no need to have real TOS pages, you can put anything there.
