### ISSUE TITLE
Not able to see services

### ISSUE THREAD

**Issue by AmoghSaxena** [inovector/mixpost#110]
### Steps to reproduce the problem

1. Installed Mixpost using a docker installation method mentioned on the document page
2. Login with the default credentials
3. Unable to see other services like LinkedIn, Pintrest etc.
...

I am only able to see Twitter, Facebook and Tenor services but not linkedin

Can someone guide me on that?
![image](https://github.com/user-attachments/assets/a08da361-59d8-47db-8cab-ded1e98fe7be)

### Expected behaviour

Should show LinkedIn service 

### Actual behaviour

Not showing it

### Detailed description

I am only able to see Twitter, Facebook and Tenor services but not linkedin

Can someone guide me on that?
![image](https://github.com/user-attachments/assets/a08da361-59d8-47db-8cab-ded1e98fe7be)

### Specifications

latest

**Comment by lao9s** [comment]
LinkedIn is only supported by Mixpost Pro

**Comment by valensto** [comment]
Please update documentation then 
![CleanShot 2024-12-14 at 14 49 09](https://github.com/user-attachments/assets/29730430-edc1-4c59-aa35-b19beff78b1f)
