### ISSUE TITLE
filesize(): stat failed

### ISSUE THREAD

**Issue by deevus** [inovector/mixpost#111]
### Steps to reproduce the problem

I am using an S3-compatible API for storage. When trying to post to Twitter, I get this error:

```
[ "filesize(): stat failed for https://s3.us-east-005.backblazeb2.com/doublewordlabs-mixpost-storage/08-2024/jZCuVBRD72xETfX87c50JTc3TljF45WaQBajeHHS.mp4" ]
```

[Link to the file](https://s3.us-east-005.backblazeb2.com/doublewordlabs-mixpost-storage/08-2024/jZCuVBRD72xETfX87c50JTc3TljF45WaQBajeHHS.mp4)

According to the [PHP docs](https://www.php.net/manual/en/function.filesize.php), under the hood this uses the [HTTP wrapper](https://www.php.net/manual/en/wrappers.http.php), which does not support `stat()`

### Expected behaviour

I can post a video to Twitter

### Actual behaviour

I cannot post a video to Twitter

### Specifications

Mixpost Lite 1.71.0

**Comment by deevus** [comment]
It looks like the calling function actually passes the `total_bytes` parameter, so it may be fixed by not making the `filesize()` call if `total_bytes` was already passed in through `$parameters`

**Comment by GlobeMarket** [comment]
Modifique o código para verificar se o parâmetro total_bytes está presente antes de chamar filesize(). Se total_bytes já estiver definido, pule a chamada para filesize().
