### ISSUE TITLE
Error with X callback?

### ISSUE THREAD

**Issue by fergalmoran** [inovector/mixpost#116]
### Steps to reproduce the problem

Add X service with correct API Key & API Secret

Add account.
Choose X profile.
Redirected to X authorize page.
Click "Authorize app"

Redirected to mixpost error page "Undefined property: stdClass::$data"

### Expected behaviour

X account should have been added

### Actual behaviour

Undefined property: stdClass::$data`

### Detailed description

Trying to add X account - get redirected to the Authorize page, click "Authorize App" and get redirected back to site with error

```Undefined property: stdClass::$data```

Error page [here](https://flareapp.io/share/x5MYb3X5)

### Specifications

Mixpost 1.7.2.0

**Comment by lao9s** [comment]
Hi @fergalmoran 
I couldn’t identify this bug. Were you able to figure it out?

**Comment by fergalmoran** [comment]
@lao9s I'm afraid I haven't - I've given up on X as a platform though so I'm not really interested in it any more.

**Comment by TotalLag** [comment]
@lao9s Can we get this reopened? I also am running into issues trying to get this setup today.

Lite version: 1.7.2.0

**Comment by lao9s** [comment]
@TotalLag I’m upgrading Mixpost Lite to v2, and this issue will be resolved in the process.
