### ISSUE TITLE
Pictures not displaying

### ISSUE THREAD

**Issue by aeonoea** [inovector/mixpost#118]
### Steps to reproduce the problem

Hi, I succesfully set up Mixpost and connected Facebook.

However, user uploaded pictures will not display in the app.

I've already followed the troubleshooting guide for this topic, checked APP_URL and tried to recreate the symbolic link:

php artisan storage:link

   ERROR  The [public/storage] link already exists.  

When I go to the mounted docker folder, I can see that Mixpost creates folders and files for the uploaded pictures.

### Expected behaviour

Pictures showing

### Actual behaviour

Pictures not showing

### Specifications

Latest release running with Docker, as for browser tried with various
![Screenshot 2024-10-14 at 12 42 21](https://github.com/user-attachments/assets/bb478be9-35c5-4b9f-8f6e-d06c1664830e)

**Comment by lao9s** [comment]
Can you inspect what URL you have on the broken image?

**Comment by aeonoea** [comment]
I just revisited the issue and for some reason it solved itself ;)

Probably because the container was restarted...
