### ISSUE TITLE
Schdule a post and replies

### ISSUE THREAD

**Issue by viezel** [inovector/mixpost#13]
Twitter threads or LinkedIn posts where the first reply is a link would be beneficial.

**Comment by lao9s** [comment]
Threads and replies will be available on the Mixpost PRO version. This repository is the lite version of Mixpost PRO.

**Comment by guillmz** [comment]
Hi @lao9s 

When you are going to release Mixpost PRO?

Regards

**Comment by lao9s** [comment]
Hi @guillmz 
Mixpost PRO Team by the end of Q1, 2023, and Mixpost PRO SaaS by the end of Q2, 2023.

If you are interested, there's an Early Access Deal: https://mixpost.app/pricing
