### ISSUE TITLE
Documented composer require won't work and artisan is not located

### ISSUE THREAD

**Issue by jonathands** [inovector/mixpost#17]
Composer require inovector/mixpost won't work due to minimum stability being  `stable`  by default

`I had to use composer require inovector/mixpost:dev-main:dev-main`

also

`php artisan vendor:publish --tag="mixpost-migrations" `

Does not work for me with either the composer require or cloning and running composer install

`Could not open input file: artisan`

My environment

php -v
PHP 8.1.2-1ubuntu2.10 (cli) (built: Jan 16 2023 15:19:49) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.2, Copyright (c) Zend Technologies
    with Zend OPcache v8.1.2-1ubuntu2.10, Copyright (c), by Zend Technologies

**Comment by lao9s** [comment]
Hi @jonathands ,
Thank you for trying to install Mixpost, but it's not been released yet.

But there is something I want you to know: This repository is not a standalone app, this repository contains the package for the Laravel application. All these commands, like `php artisan vendor:publish --tag="mixpost-migrations"` are executed from Laravel project with the Mixpost package installed. You can consider this repository as the core.

This is the reason why you can't use `artisan` commands.

When I'll release it, I'll create a new repository for the Standalone app and you be available to install without worry about installing Laravel, Mixpost package, and so on...
