### ISSUE TITLE
Feature Request - Address book

### ISSUE THREAD

**Issue by JustDalek** [inovector/mixpost#18]
Hello!, 

I would like to submit a feature request for consideration. 

As I await the release of mixpost, I am using an alternate platform to handle my management needs.

One issue when I need to post something that addresses an existing creator and out partnership is that not all creators out there are good at proper cross-platform branding, so tagging them (@username) per-platform can be a bit tedious.

For this, I was wondering if an address book feature could be implemented where we can create a profile for creators we frequently work with, and pre-define their handles per-social network?

This way, instead of typing out their name per-network, we could choose from addressbook and mixpost would be able to insert the correct handle.

 Simply an Idea, thank you for your time!

**Comment by lao9s** [comment]
This feature is planned for [Mixpost Pro & Enterprise](https://roadmap.mixpost.app/projects/mixpost-pro/items/63-address-book)
