### ISSUE TITLE
Feature Request - Frequently used Hashtags

### ISSUE THREAD

**Issue by JustDalek** [inovector/mixpost#19]
Hello!, 

This request is a bit simpler, but it would be nice if Mixpost allowed us to either pre-define an array of hashtags, or if it remembers and counts the most used hashtags and allows us to post using that!

I am thinking this should work the same way email distribution lists do. Meaning that you can store a pre-defined group, and selecting that group simply pastes the hashtags at the end of your post, allowing you to keep them as-is, or having the ability to add/remove hashtags. 

Thank you for your consideration!

**Comment by lao9s** [comment]
'**Hashtag groups**' will be included in the Pro version. It is indicated on the website in the comparison table.

<img width="1003" alt="Screenshot 2023-02-13 at 17 09 04" src="https://user-images.githubusercontent.com/3392129/218495216-ae2756bd-7331-49c1-9904-3fdfa5f5597c.png">

**Comment by JustDalek** [comment]
Ah fantastic thank you!
