### ISSUE TITLE
"Feature" Request, clean up published files

### ISSUE THREAD

**Issue by Quadrubo** [inovector/mixpost#29]
### Detailed description

Hello,
at the time of writing this when installing mixpost publishes 68 files, almost none of which should be necessary. In other packages, the tables are all created with one migration file which would clean up at least 13 migrations.
Publishing stuff is, in my opinion generally also a bad idea because of future updates.
Thanks!

**Comment by lao9s** [comment]
Hi, @Quadrubo

Most published files are CSS & JS files. There is no way to run a Laravel package that has a UI without publishing that kind of asset.

About migrations: I will think about it, maybe I'll put it all in one migration file.
