### ISSUE TITLE
Support for PHP 8.0

### ISSUE THREAD

**Issue by mihaisolomon** [inovector/mixpost#3]
Hey,

Another thing that I saw is that you have support only for php 8.1.

Could you add support also for PHP 8.0?

**Comment by lao9s** [comment]
Hi,
I think yes, but I have to test if any dependencies packages didn't require the PHP 8.1

**Comment by mihaisolomon** [comment]
I installed on my local machine (I have 8.0) and I didn't have any issues with any dependencies.

**Comment by lao9s** [comment]
If no issues, I definitely will add support for PHP 8.0

**Comment by mihaisolomon** [comment]
I'm closing this because it will not be possible to have support for 8.0 . There are some features from 8.1.

**Comment by lao9s** [comment]
Yes, Enum casting is only available for PHP 8.1+.
