### ISSUE TITLE
Mixpost on docker 500 error with login attempt

### ISSUE THREAD

**Issue by robetus** [inovector/mixpost#31]
### Detailed description

I installed mixpost from docker hub and got to the login screen, now what? I tried user: example@mail.com and password: password, it loads for a few seconds and then gives a 500 error. Is mixpost Auth installed with the docker image? If not can it be created?

**Comment by robetus** [comment]
I run
`php artisan mixpost-auth:create`
and get 
<pre>
Illuminate\Database\QueryException 

  SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo for mysql failed: Name or service not known (Connection: mysql, SQL: select exists(select * from `users` where `email` = tester@testing.com) as `exists`)

  at vendor/laravel/framework/src/Illuminate/Database/Connection.php:760
    756▕         // If an exception occurs when attempting to run a query, we'll format the error
    757▕         // message to include the bindings with SQL, which will make this exception a
    758▕         // lot more helpful to the developer instead of just the database's errors.
    759▕         catch (Exception $e) {
  ➜ 760▕             throw new QueryException(
    761▕                 $this->getName(), $query, $this->prepareBindings($bindings), $e
    762▕             );
    763▕         }
    764▕     }

      +32 vendor frames 

  33  artisan:35
      Illuminate\Foundation\Console\Kernel::handle()
</pre>
For some reason I can't get mixpost to connect to the running mysql docker container.

**Comment by lao9s** [comment]
Hi @robetus ,
Maybe are you trying to run `php artisan mixpost-auth:create` outside of the container? You have to run this command inside the docker container. 

Another thought I have: 
Looks like you forgot to populate your DB_* environments and the Mixpost couldn't connect to the MySQL service.

**Comment by robetus** [comment]
Hi @lao9s thanks for the reply. For sure the command is being run inside the container and the environmental variables have been set correctly and checked. I'm going to install another container to see if I can get the mysql container to connect.

**Comment by robetus** [comment]
I got it working, I switched to running inside a linux container. Now I'm figuring out how to install an SSL cert for the domain. Closing this issue.
