### ISSUE TITLE
Latest docker hub image is broken

### ISSUE THREAD

**Issue by robetus** [inovector/mixpost#36]
### Detailed description

Getting a 500 error with a new docker pull install from default yml file.

**Comment by lao9s** [comment]
Hi @robetus,

We did some important changes to the docker image and now you have to put the `APP_KEY` environment variable with a generated base64 secret key.

Please, see the new `docker-compose.yml` at [https://hub.docker.com/repository/docker/inovector/mixpost/general](https://hub.docker.com/repository/docker/inovector/mixpost/general), pull the image and start the docker containers.

And after this action, you will need to re-enter your service credentials and re-connect the social accounts. Please read the "Important information" there.

**Comment by robetus** [comment]
Thank you for update I over looked this.
