### ISSUE TITLE
docker compose installation example

### ISSUE THREAD

**Issue by IzioDev** [inovector/mixpost#38]
### Detailed description

Hi,

Would it be possible to add docker compose installation example in order to facilitate the installation process?

I'm trying to create one for mixpost, but i'm not familiar with best-way to do this with PHP (lightweigh images etc..),
So I might end-up with something, that could be improved if needed.

**Comment by IzioDev** [comment]
ok nvm, I just found it here https://hub.docker.com/r/inovector/mixpost

**Comment by saschafoerster** [comment]
And here: https://inovector.notion.site/Install-Mixpost-Lite-with-Docker-857c3c2abedd4b69a641556c16b7da35
Maybe the docker-compose file should just be part of the repository? :)

**Comment by IzioDev** [comment]
It's usual to have docker compose file in the repository, however it's up to the project members to decide what to do👍
