### ISSUE TITLE
Logout and Instagram

### ISSUE THREAD

**Issue by robetus** [inovector/mixpost#39]
### Detailed description

I've installed the light version and I don't see instagram anywhere, is this being added later then? Several social media outlets are sited on the website but I don't see them.

Also, is there no way to logout of the app? Maybe I'm missing it.

**Comment by lao9s** [comment]
Instagram is not included in the Lite version, it is only in Pro. Take a look at the pricing page in the Comparision section: [https://mixpost.app/pricing](https://mixpost.app/pricing)

<img width="1295" alt="Screenshot 2023-03-22 at 09 54 23" src="https://user-images.githubusercontent.com/3392129/226835984-74e0db45-ea24-45eb-a687-40cb1367809c.png">

"The logout" is in the roadmap and will implement soon!

**Comment by robetus** [comment]
Okay great, can't wait for the pro version to be released.
