### ISSUE TITLE
Qualifier can be replaced with an import 

### ISSUE THREAD

**Issue by mihaisolomon** [inovector/mixpost#4]
Hey,

Question. 

Why you are not using imports? The code will look cleaner. I saw it used in a lot of places like this. Any reasons why?
 
https://github.com/inovector/mixpost/blob/7ac6709f9bd133b1f078fdc93e330f4033590dbd/src/Http/Controllers/ScheduleController.php#L10

**Comment by lao9s** [comment]
Hi,
No reason, I added this with IDE (PhpStorm) and I did;t saw a reason to import them. But, you are right, the code will like much cleaner, I'll import them
Thanks

**Comment by lao9s** [comment]
Done
