### ISSUE TITLE
Feature Request - Makes Teams Per Group of Account

### ISSUE THREAD

**Issue by DrMxrcy** [inovector/mixpost#40]
### Detailed description

Hello!

I am currently using another app to manage my social media till mixpost comes out, but there's a feature that has been critical to me, and I never saw that mentioned

That Feature is Being Able to Create Teams, and have that team only have Access to those accounts that you allow.

Users could be assigned to multiple teams, or just one. 

It would allow companies with a few different brands, to separate per team.

Let me know if you have any questions!

**Comment by lao9s** [comment]
Hi @DrMxrcy,
We call this feature "Workspaces", and it will be available on Mixpost Pro. With workspaces, you can do the same thing, create a new workspace, and assign users and these users will have access only to resources(posts, tags, social accounts) belonging to that workspace.

**Comment by DrMxrcy** [comment]
Perfect! Excited to see this in pro!
