### ISSUE TITLE
Question about running via docker-compose.yml

### ISSUE THREAD

**Issue by ovizii** [inovector/mixpost#42]
### Detailed description

I've been following this how-to :https://inovector.notion.site/Install-Mixpost-Lite-with-Docker-857c3c2abedd4b69a641556c16b7da35 

It looks like mixpost isn't connecting to the MySQL DB. I'm sure this is the case because I modified my docker-compose.yml file, and I was wondering why there seems to be no parameter named "DB_HOST" which seems to hint that the MySQL server name is somehow hard-coded somewhere?

Any hints are welcome.

**Comment by ovizii** [comment]
btw. same goes for redis: can we have an environmental variable for REDIS_HOST please?

**Comment by lao9s** [comment]
Hi @ovizii,
Yes, you can put a `REDIS_HOST` or `DB_HOST` environment variable, these variables are optional. I just edited the documentation by the way.

Anyway, there is the up-to-date [doc](https://hub.docker.com/r/inovector/mixpost)

**Comment by ovizii** [comment]
Ah, thanks, I see the link you posted actually listed those variables. Looks like I made a good guess, thanks, problem solved.
