### ISSUE TITLE
Is there a way to mention LinkedIn contacts?

### ISSUE THREAD

**Issue by juekr** [inovector/mixpost#48]
### Detailed description

Basically the title says it all. In Instagram, I can just type @profile_name – but I don't know if that is the way to go for Linkedin. I guess it is not really possible to implement auto-completion when mentioning somebody like it is in almost any native social-media app, or is it?

**Comment by lao9s** [comment]
Hi @juekr 
Mixpost Lite does not support Instagram/LinkedIn, or are you a Pro/Enterprise customer?

There is a feature in the roadmap: https://roadmap.mixpost.app/projects/mixpost-pro/items/63-address-book

**Comment by juekr** [comment]
Yes I am.
