### ISSUE TITLE
Qualifier can be replaced with an import Part 2

### ISSUE THREAD

**Issue by mihaisolomon** [inovector/mixpost#5]
Hey,

I missed one more file, it's a model: 

https://github.com/inovector/mixpost/blob/8ce79d68d3bfdf53c0cbb05fec8b399fda59b9b9/src/Model/Post.php#L23

https://github.com/inovector/mixpost/blob/8ce79d68d3bfdf53c0cbb05fec8b399fda59b9b9/src/Model/Post.php#L28

**Comment by lao9s** [comment]
Done. Thanks.
