### ISSUE TITLE
How can I change the description of the fields?

### ISSUE THREAD

**Issue by samee-sys** [inovector/mixpost#53]
### Detailed description

I tried to change description on the settings page under js folder. But it is not reflecting. How should I compile the assets. Is it possible to customize? Thank you.

**Comment by yunusemreata** [comment]
I would like to edit files, is it possible for us to do that? Thank you.

**Comment by lao9s** [comment]
@samee-sys 
`npm run build`

**Comment by lao9s** [comment]
@yunusemreata Yes. But then you have to compile the assets with `npm run build`
