### ISSUE TITLE
FFMPEG library install docs

### ISSUE THREAD

**Issue by mihaisolomon** [inovector/mixpost#6]
Hey,

I took a look over your last commit and it would be nice to add to docs a link for how to install FFMPEG library for your machine like in here: https://github.com/PHP-FFMpeg/PHP-FFMpeg#how-this-library-works

https://github.com/inovector/mixpost/blob/2da02e09468b5aa7bccec01495b783306420b597/composer.json#L26

**Comment by lao9s** [comment]
Done ✅
