### ISSUE TITLE
Getting 'Internal Server Error 500' after deploying Mixpost via docker compose

### ISSUE THREAD

**Issue by kkailaasa** [inovector/mixpost#60]
### Detailed description

Using the docker compose given @ https://registry.hub.docker.com/r/inovector/mixpost, i have been able to deploy the application and with all the containers giving running/healthy status. But when I access the site, I'm getting an internal 500 server error.

When going through the logs of the mysql container, I find the following:
```
mysqladmin: [Warning] Using a password on the command line interface can be insecure. mysqladmin: connect to server at 'localhost' failed error: 'Access denied for user 'root'@'localhost' (using password: YES)'
```

Anyone know how to resolve this?

**Comment by lao9s** [comment]
Hi @kkailaasa 
Check if the database credentials are the same on `mixpost` and `mysql` service.
<img width="653" alt="Screenshot 2023-10-23 at 11 22 28" src="https://github.com/inovector/mixpost/assets/3392129/cf155b54-8cc3-40b6-a551-98e7e147bf82">

If the credentials are the same, try a fresh installation by executing:

`docker-compose down -v`
`docker-compose up -d`

**Comment by kkailaasa** [comment]
Yes, I have double-checked this everytime I tried deploying (around 5 times till now), making sure the creds are the same in all three places but still got the same error. Each time I did, I made sure I cleared the old volumes before running the compose.

**Comment by lao9s** [comment]
@kkailaasa  Did you generate/copy the `APP_KEY` correctly? You need to generate with this [tool](https://mixpost.app/encryption-key-generator).

**Comment by ckerfurt** [comment]
Is there an update here yet? I get the same error.

**Comment by lao9s** [comment]
Please, send a screenshot of error

**Comment by Artmorse** [comment]
I found this repository: https://github.com/macagua/mixpost_docker, but it seems to be outdated.
Can you share the latest version of the documentation?

**Comment by lao9s** [comment]
> I found this repository: https://github.com/macagua/mixpost_docker, but it seems to be outdated. Can you share the latest version of the documentation?

https://hub.docker.com/r/inovector/mixpost
