### ISSUE TITLE
Census.gov Social Media Sharing

### ISSUE THREAD

**Issue by ekk88d** [inovector/mixpost#61]
### Detailed description

Hi, I have tried paid subscriptions to Buffer, HubSpot and Loomly. None of these services are able to parse Census.gov links.

One Buffer support agent said that they simply get a 403 code returned for that domain and then he closed the ticket.

Before I go down the road of installing, configuring, and then upgrading, I wanted to see if Mixpost can successfully parse these links. I'm sure there are other sites with the same restrictions.

After pasting the link in the post creation window, I'm just looking to pull in the link's images and text snippet. Then, I can choose which images to share from the thumbnails of the scraped images - like you'd expect from sites without these limitations.

If Census.gov is an example of a hard restriction on bypassing successful link parsing, is there a particular HTTP Request being blocked? I'm not familiar with the network inspection tools needed to find out.

**Comment by lao9s** [comment]
Hi,
Mixpost doesn't have a feature to parse the url.
