### ISSUE TITLE
Docs for adding a social provider?

### ISSUE THREAD

**Issue by cweagans** [inovector/mixpost#64]
### Detailed description

I want to add Meetup.com as a provider. I want to schedule a meetup event to go live at some particular time and have other social media posts promoting the event getting posted at the same time.

Are custom social providers something that you'd want to support? I'm happy to do the work to build out the provider, but I also don't want it to break with future updates. It's something that I'd be open to contributing back as well, provided that it's available in the free version.

**Comment by cweagans** [comment]
Another use case: TikTok will not allow me to get API access for a private app. I could work around this by adding a different TikTok provider that automates the web interface somehow.

**Comment by lao9s** [comment]
Hi @cweagans 
If you can help with Meetup.com integration, that would be great. It will remain in the free version.

About TikTok, can you give more details, please?

**Comment by lao9s** [comment]
@cweagans 

Unfortunately, I don't have documentation for developers. Just follow the actual flow integration of a social provider.

Re TikTok: you can run Mixpost on a public domain and generate some pages (home, privacy, terms...) from admin, and they will approve your app.

**Comment by cweagans** [comment]
> Unfortunately, I don't have documentation for developers. Just follow the actual flow integration of a social provider.

No problem. I have a WIP PR open that I'll keep working on as I have time. Hopefully, it will serve as a good example for other devs in the future.

> Re TikTok: you can run Mixpost on a public domain and generate some pages (home, privacy, terms...) from admin, and they will approve your app.

I'm running it on a public domain, have all of the pages generated, etc. I've been going back and forth with them for over a week now. They've been extremely difficult to work with. I'll figure it out though - it's not a big deal. Just takes time.

**Comment by cweagans** [comment]
(I just realized that I hadn't actually opened the PR, so I did that just now: https://github.com/inovector/mixpost/pull/69)
