### ISSUE TITLE
Twitter/X character count is incorrect

### ISSUE THREAD

**Issue by HammyHavoc** [inovector/mixpost#65]
### Steps to reproduce the problem

1. Write a post using all the characters available down to `0`

### Expected behaviour

For the count to be correct

### Actual behaviour

The post failed to be published due to there being too many characters

### Detailed description

I tried to post the following:

```
I've been a fan of RSS for almost a quarter of a century—IMO, it keeps the modern web useable. Love @FreshRSS.

Recommend me your favourite RSS feeds! Even if they're yours, I want to know about them!

Installing KOReader on a hacked Kindle to use with @wallabagapp. #FOSS #IndieWeb
```

I got this error:

`[ { "errors": [ { "parameters": { "text": [ "I've been a fan of RSS for almost a quarter of a century—IMO, it keeps the modern web useable. Love @FreshRSS.\n\nRecommend me your favourite RSS feeds! Even if they're yours, I want to know about them!\n\nInstalling KOReader on a hacked Kindle to use with @wallabagapp. #FOSS #IndieWeb\n" ] }, "message": "Your Tweet text is too long. For more information on how Twitter determines text length see https://github.com/twitter/twitter-text." } ], "title": "Invalid Request", "detail": "One or more parameters to your request was invalid.", "type": "https://api.twitter.com/2/problems/invalid-request" } ]`

Was actually 2 characters too long. Could it be the paragraphs?

### Specifications

Mixpost Enterprise 1.0.2.0

**Comment by lao9s** [comment]
@HammyHavoc Thank you for the report. I'll test it.

**Comment by lao9s** [comment]
@HammyHavoc Tested with your text and posted successfully with 0 characters left.
