### ISSUE TITLE
Facebook Connection Issue

### ISSUE THREAD

**Issue by ddlidded** [inovector/mixpost#71]
### Steps to reproduce the problem

There is no option to select another API version other than v18.0. The versions suggested in the documentation are not available for selection, so attempting to add a new page fails.

<img width="696" alt="Screenshot 2023-12-16 at 7 36 49 AM" src="https://github.com/inovector/mixpost/assets/63270906/e740886e-bdeb-48e1-8859-217c9ce241a4">
<img width="1039" alt="Screenshot 2023-12-16 at 7 37 04 AM" src="https://github.com/inovector/mixpost/assets/63270906/233346ea-f2c7-4e01-ab41-251533867fb1">

### Expected behaviour

Facebook Page Should Be Added

### Actual behaviour

Failed to Connect Facebook Page

### Specifications

inovector/mixpost:v1.1.3

**Comment by lao9s** [comment]
@ddlidded the problem is not in the version.

- Check if you entered the correct domain in your FB app.
- Check if the product is Facebook Login, not Facebook Login for Business.
- Check if you entered the correct callback URLs.

**Comment by Gibigbig** [comment]
> @ddlidded the problem is not in the version.
> 
> * Check if you entered the correct domain in your FB app.
> * Check if the product is Facebook Login, not Facebook Login for Business.
> * Check if you entered the correct callback URLs.

Ran into a a similar issue. 
My FB app has the facebook login addon and is correct. My environment is localhost. No callback needs to be specified in facebook callbacks. 

Any idea on how to fix this?

**Comment by lao9s** [comment]
> No callback needs to be specified in facebook callbacks.

Why? You should put the callback link.

Go to the “Valid OAuth Redirect URIs” input and enter these callback URLs:

https://your-app-url.com/mixpost/callback/facebook_page
https://your-app-url.com/mixpost/callback/facebook_group

**Comment by pratikkuikel** [comment]
i can't find facebook login product, Facebook Login for Business is the only login product available in my case.

**Comment by lao9s** [comment]
@pratikkuikel 

From the doc:
1. On the left sidebar, click on “Add product” and select “Facebook Login” or “Facebook Login for Business.”
2. If you selected “Facebook Login for Business”, you need to Switch to the standard “Facebook Login”.

https://docs.inovector.com/books/integration-of-social-platforms/page/facebook#bkmrk-step-2%3A-create-a-new

**Comment by uhlhosting** [comment]
> > @ddlidded the problem is not in the version.
> > 
> > * Check if you entered the correct domain in your FB app.
> > * Check if the product is Facebook Login, not Facebook Login for Business.
> > * Check if you entered the correct callback URLs.
> 
> Ran into a a similar issue. My FB app has the facebook login addon and is correct. My environment is localhost. No callback needs to be specified in facebook callbacks.
> 
> Any idea on how to fix this?

You cannot expect Facebook to connect to your localhost ain't you?
