### ISSUE TITLE
What are the minimum system hardware requirements for the server: CPU, RAM...

### ISSUE THREAD

**Issue by TxTechnician** [inovector/mixpost#72]
### Detailed description

The requirements for PHP, Larvel... etc are listed.  But not the requirements for the hardware.

**Comment by uhlhosting** [comment]
@TxTechnician these will vary based on multiple factors such as accounts/organizations number of files used,  size of DB. Yet id say you can easy start with 2GB ram and see from there.

**Comment by TxTechnician** [comment]
Got it, thank you.  Running a VPS and set it to 1 cpu 2 gb ram.  I'll upgrade from there.
