### ISSUE TITLE
No Instagram accounts found.

### ISSUE THREAD

**Issue by TxTechnician** [inovector/mixpost#73]
### Detailed description

I setup Instagram by using the login with Facebook feature.  Then turned the personal Insta account into a business account.  

Facebook, and my Facebook business pages loaded fine in MixPost.  But when I go to add Instagram.  Nothing is found.

**Comment by uhlhosting** [comment]
@TxTechnician you need you Facebook business approved!

**Comment by lao9s** [comment]
@TxTechnician 

- Check if you gave consent to all pages when you connected your Facebook account.
- Check if your Instagram account is attached to a Facebook page.

**Comment by lao9s** [comment]
@TxTechnician 

Also, convert your Instagram account to a business account
