### ISSUE TITLE
TikTok Audit not passing - UX seems to fail new requirements

### ISSUE THREAD

**Issue by kurucu** [inovector/mixpost#74]
### Steps to reproduce the problem

1. Apply for audit to post directly to TikTok
2. Provide user flow video & document for your Mixpost integration
3. TikTok says audit fails..

### Expected behaviour

TikTok should recognise app elements that address items in their requirements.

### Actual behaviour

They do not (appear) to exist in Mixpost's TikTok integration

### Detailed description

I am led here but the audit team:

https://developers.tiktok.com/doc/content-sharing-guidelines#required_ux_implementation_in_your_app

If I look at this guidance, these are the things I can't see:

# Required UX Implementation in Your App

1) API Clients must retrieve the latest creator info when rendering the Post to TikTok page.

a. ✅ The upload page must display the creator's nickname, so users are aware of which TikTok account the content will be uploaded to. 

b. ✅ When the creator_info API returns that the creator can not make more posts at this moment, API Clients must stop the current publishing attempt and prompt users to try again later.

c. ❓ When posting a video, API clients must check if the duration of the to-be-posted video follows the max_video_post_duration_sec returned in the creator_info API.

2) API Clients must allow users to enter or select the following metadata for a post:

a. ⚠️ Title

b. ⚠️ Privacy Status, with the following mandatory requirements:

The options listed in the UX must follow the privacy_level_options returned in the creator_info API.
Users must manually select the privacy status from a dropdown and there should be no default value.
c. ⚠️ Interaction Ability - Allow Comment, Duet, and Stitch - with the following style requirements:

If the creator_info API returns that one or more of these interactions have been disabled in their app settings, your UX must disable and grey out the checkbox for the interaction.
Users must manually turn on these interaction settings and none should be checked by default.
Duet and Stitch features are not applicable to photo posts. So, for Photo Posts, only 'Allow Comment' can be displayed in the UX.
NOTE: Before allowing users to post through your platform, there should be a declaration asking for a user's consent before the publish button. It should clearly state: "By posting, you agree to TikTok's [Music Usage Confirmation](https://www.tiktok.com/legal/page/global/music-usage-confirmation/en)"

3) API Clients must allow users to disclose Commercial Content:

a. ⚠️ Content Disclosure Setting - Indicate whether this content promotes yourself, a brand, product or service, with this feature turned off by default. Enabling this feature will display checkboxes for "Your brand" and "Branded content" below, allowing users to select their preferences.

[...]

b. Privacy Management:

⚠️  If a user wants to choose Branded Content, it is important to note that it can only be configured with visibility as public/friends.

[...]

4) Compliance requirements:

⚠️ If the user is trying to post commercial content (i.e. commercial content toggle is turned on):

[...]

5) The users of API Clients must have full awareness and control of what is being posted to their TikTok accounts.

a. ✅ API Clients should display a preview of the to-be-posted content.

b. ✅ API Clients should not add promotional watermarks/logos to creators' content. Preset text, including any text in the title field or hashtags, should be allowed to be edited by the user before posting content.

c. ✅ API Clients must only start sending content materials to TikTok after the user has expressly consent to the upload.

d. ❓ API Clients must clearly notify users that after they finish publishing their content, it may take a few minutes for the content to process and be visible on their profile.

e. ❓ API clients should poll the [publish/status/fetch API](https://developers.tiktok.com/doc/content-posting-api-reference-get-video-status) or handle status update webhooks, so users can understand the status of their posts.

### Specifications

Mixpost Pro v1.2.5 (v1.4.3)

**Comment by uhlhosting** [comment]
Yes i have failed to pass in past 2 months. I had to give up trying for now. Yet in same time it other people got accepted.

**Comment by uhlhosting** [comment]
@lao9s how is the status on this?

**Comment by lao9s** [comment]
Fixed in v2.
