### ISSUE TITLE
OAuth Exception: Unsupported Image Format

### ISSUE THREAD

**Issue by juekr** [inovector/mixpost#88]
### Steps to reproduce the problem

- Created a new post
- Selected Instagram (post)
- Uploaded a media item (I've tried .png and .jpg) and added text
- Tried to publish it immediately

### Expected behaviour

Publication of image to Instagram

### Actual behaviour

Posting fails

### Detailed description

I've installed MixPost's new version on a new server. Completely fresh install. I've even created a new app at Meta for Developers. But whatever I do, I seem unable to post anything to Instagram. (I can connect to my accounts, but posting fails). I've tried a PNG image with 1080x1080 as well as a JPEG version with the same dimensions. File size 200 KB / 250 KB. No luck.

<img width="651" alt="image" src="https://github.com/inovector/mixpost/assets/24369804/39a82f5b-f644-417f-a503-dccd221430dd">
 

### Specifications

User agent	Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36
PHP	8.2.17
Laravel	10.48.4
Horizon	5.23.2.0
Mixpost	2.0.1.0

**Comment by lao9s** [comment]
Hi @juekr 

Instagram API requires that the images should be publicly accessible. 

Possible causes:
- Your instance is on **localhost**
- You use **CloudFlare** authentication.

**Comment by juekr** [comment]
Hey there. Thanks for commenting. I don't use localhost, but a publicly reachable domain. CloudFlare might be involved, I am not sure. How can I verify that? And what could be a solution?

**Comment by juekr** [comment]
I am not really sure how to do that. I am using Cloudron with an app proxy pointing to Docker running Mixpost. By I am in no way an experienced sysadmin 🤷‍♂️

**Comment by lao9s** [comment]
@juekr let's continue the discussion in PM. I'm online right now and I can take a look.

PM https://indieweb.social/@lao9s
