### ISSUE TITLE
OAuthException : Invalid parameter | Unsupported media type VIDEO

### ISSUE THREAD

**Issue by black-jmyntrn** [inovector/mixpost#89]
### Steps to reproduce the problem

1. Create new post
2. Selected Facebook Instagram Youtue
3. Select uploaded Video
4. Tried to publish immediatley
...
![image](https://github.com/inovector/mixpost/assets/47804647/38e5b1a8-12d5-48ee-b5ff-b774b831a19f)

### Expected behaviour

Post Video To Instagram

### Actual behaviour

Video only posted to Youtube and Facebook. Post to Instagram failed

### Detailed description

Upgraded to the latest version and went to test first post. I uploaded one recently created video then proceeded to post. After selecting Instagram, Facebook the Youtube the new AI feature was used and inserted then post now was clicked. After sometime I went to check the post on the dashboard and its now showing failed even with 2 of 3 services able to post the video. 

### Specifications

User agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36
-- | --
PHP | 8.2.17
Laravel | 10.48.7
Horizon | 5.24.0.0
Mixpost | 2.0.2.0

**Comment by black-jmyntrn** [comment]
one thing to note, I was never given the Instagram Page options selection option when using this. After selecting and unselecting an account in the opper left I now see the options box.

**Comment by lao9s** [comment]
Unfortunately, Facebook turns down the possibility of creating a post video. They allow to upload videos only as a reel which is only available in Mixpost Pro.

But we will do in Lite that the video is considered as a reel.

**Comment by black-jmyntrn** [comment]
this is the thing, the video was posted to FB with no issue, it was posting to IG which was the error. I think the flow when making a new post, is somewhere in there you can post content, and the selection box for the post type doesn't display so I ended up publishing the content but without making the post type selection.
