### ISSUE TITLE
is this app still being developed?

### ISSUE THREAD

**Issue by chymian** [inovector/mixpost#9]
hi, 
since the last commit is 3 month ago, Is this app still being developed?

BTW:
the template for new issue - ask a question gives a 404

**Comment by muisawe** [comment]
I think no he is not working on it right now. but you could create a fork and add your update 😃😃

**Comment by mihaisolomon** [comment]
Hey,

All the work it's done on the develop branch, check that out.

**Comment by lao9s** [comment]
Hi @chymian,
As @mihaisolomon said, all works are on develop branch. I am working hard to release it as soon as possible.
Make sure to sign up at https://mixpost.app to be notified when it's released.

**Comment by chymian** [comment]
> all works are on develop branch. 

thx, I gonna check that out

>I am working hard to release it as soon as possible.

wanna have some real live testers, let me know…
any ETA?

> Make sure to sign up at https://mixpost.app/ to be notified when it's released.

sure, already done.

**Comment by saschafoerster** [comment]
Cool! I am looking forward to it. Count me in as early bird tester.

**Comment by lao9s** [comment]
> Count me in as early bird tester.

Sure!

**Comment by lao9s** [comment]
> any ETA?

Sorry, but what is ETA? )

**Comment by mihaisolomon** [comment]
@lao9s Estimated time when the app is ready.

**Comment by lao9s** [comment]
> Estimated time when the app is ready.

@mihaisolomon Thanks for the explanation.

> any ETA?

@chymian I estimate it will be released by the end of November, but it is not exact.

**Comment by chymian** [comment]
@lao9s 
> @chymian I estimate it will be released by the end of November, but it is not exact.
cool, let me know when you need beta-tester.

**Comment by lao9s** [comment]
Hi @chymian 

I think it would be interesting for you to know that I launched it:

Install Mixpost:
    •    In an existing Laravel app: [https://github.com/inovector/](https://github.com/inovector/)
    •    As a standalone app: [https://github.com/inovector/MixpostApp](https://github.com/inovector/MixpostApp)
    •    With a Docker image: [https://hub.docker.com/r/inovector/](https://hub.docker.com/r/inovector/)
