### ISSUE TITLE
mixpost configured with no ssl behind Cloudflare Tunnel

### ISSUE THREAD

**Issue by plasticpippo** [inovector/mixpost#95]
### Detailed description

Hi, i have susccessfully setup mixpost and i was just testing the docker install on a Debian Bookworm VM.
I used the no SSL configuration as suggested on the documentation but i could not login using simple HTTP as it was always reverting to HTTPS in the browser.
So I tried to set it up using Cloudflare tunneling. I managed to get to the login screen, but when I enter username and password i always receive the message "internal error has occurred" and then just a button "go home"

Am I doing something wrong?
I was at least expecting to see some sort initial dashboard using a local 192.168.x.x address over http but no joy there either!

**Comment by lao9s** [comment]
What do you have in `APP_URL`?

**Comment by plasticpippo** [comment]
Hey,
thanks for your reply

What do you have in APP_URL?
APP_URL=https://${APP_DOMAIN}

**Comment by plasticpippo** [comment]
i changed https:// to http:// and it's all good now. Thanks!
